service: scrapeogtag3-dev
provider:
  name: aws
  runtime: nodejs12.x
functions:
  scrape:
    handler: scrape/controller.scrape
    events:
      - http:
          path: /scrape
          method: post
          integration: lambda
          cors:
            origins:
              - '*'